name: Test with Etherpad 2.7.2
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call:
    uses: ./.github/workflows/ep-plugin-test.yml
    with:
      etherpad-version: "2.7.2"
